version: "3.8"

services:
  app:
    container_name: thenews.tech
    build: .
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    environment:
      - .env.development
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
