name: Run Vercel Job
on:
  schedule:
    - cron: "30 16 * * *" # 13h30 no horário de Brasília (GMT-3) -> 16h30 UTC
  workflow_dispatch:
jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: curl -X GET "https://thenews-tech-api.vercel.app/v1/run-cron"
