name: Run Vercel Job
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: curl -X GET "https://thenews-tech-api.vercel.app/v1/run-cron"
